name: Build and Lint
on:
  pull_request:
    branches:
      - 'main'
jobs:
  LintCode:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm i

      - name: Lint
        run: npm run lint
